### ISSUE TITLE
Create a verbose option

### ISSUE THREAD

**Issue by KoenDesplenter** [peng-lab/BaSiCPy#102]
Could you create a verbose option for the BaSiC object.
It would be nice to disable the logs of BaSiC since it produces a lot of log statements.

**Comment by yfukai** [comment]
Hi, thanks @KoenDesplenter for your feedback, and we're sorry for the late reply. 
Now, the default logging level is set to `warning`, which prints the log only when something wrong happened.
You can further change the log level in a standard way:
```python
import logging
logger = logging.getLogger("basicpy")
logger.setLevel(logging.DEBUG) # for the finest level
```
