### ISSUE TITLE
Role of initial_flatfield

### ISSUE THREAD

**Issue by yfukai** [peng-lab/BaSiCPy#11]
Here, I found there's a `initial_flatfield` parameter which is always set to be `False` .
https://github.com/peng-lab/PyBaSiC/blob/01d8fe1ae86f2a09ced2cd710bd3e043036deea0/pybasic/_background.py#L204
Is there any role for this? @tying84, if you remember something, would you mind commenting on this?

**Comment by Nicholas-Schaub** [comment]
This looks like it might be related to what we were discussing during the meeting today, where you could supply a starting point for the flatfield component.

**Comment by yfukai** [comment]
Pasting the reply from @tying84, 
> For initial_flatfield, I now remember at that time, I want to do estimate flatfield in a multi-resolution approach, so first estimate a rough flatfield for a small resized image, then go to higher resolution. I vaguely remember it is not that straightfoward in the iterative optimization loop. I will check it again when I rewrite the code in JAX.
