### ISSUE TITLE
Multiple Channel Correction

### ISSUE THREAD

**Issue by Nelson-Gon** [peng-lab/BaSiCPy#118]
Hi BaSiCPy team,

Awesome package. Looking at this [line](https://github.com/peng-lab/BaSiCPy/blob/93b0545dae5df3e290d0ffc9b11623ed3ca5cb8a/src/basicpy/basicpy.py#L71), I see a comment that for multichannel images, a `basic` object should be created for each channel.

I am not sure if this comment is for the end user or developers and request clarification on this. If this is intended for the end-user, perhaps there should be some warning if one runs the transform on a multichannel image in case it does affect the result. 

Thank you,
NelsonGon

**Comment by yfukai** [comment]
Hi, thanks @Nelson-Gon for pointing this out! I added the warning and updated the docstring at #119. Happy to hear your feedback on that!

**Comment by Nelson-Gon** [comment]
Looks good, thank you. Closing as it seems resolved in #119
