### ISSUE TITLE
`basic.fit()` should also return baseline intensities

### ISSUE THREAD

**Issue by yfukai** [peng-lab/BaSiCPy#14]
Considering `basic.fit()` also does the baseline fitting, the estimated baseline (for photobreaching etc...) should be returned.
example:

```python
basic=Basic()
basic.fit(train_images)
corrected, baselines = basic.predict(test_images)
# corrected, baselines = basic.fit_predict(train_images)

```

**Comment by yfukai** [comment]
merged to the broader issue and close.

**Comment by yfukai** [comment]
Reopen as the current version returns corrected images only.

**Comment by Nicholas-Schaub** [comment]
Yes, my first pass at `predict` was only to implement something straightforward. Baby steps and incremental change are easiest :)

**Comment by tdmorello** [comment]
An array of baseline values are included as a parameter of the BaSiC class (`basic.baseline`) so we do not need to return baseline with `transform`.

Can we close this issue? @yfukai @Nicholas-Schaub

**Comment by yfukai** [comment]
Yeah let's close this.
