### ISSUE TITLE
Implement a DCT abstract base class

### ISSUE THREAD

**Issue by Nicholas-Schaub** [peng-lab/BaSiCpy#15]
The discrete cosine transform is one of the core computations in BaSiC. There is interest in benchmarking the DCT from different libraries, and there may be merit to support different approaches based on dependency issues. Thus, we should institute an abstract base class that defines expected methods for different implementations.

- [ ] Create an abstract base class with methods `dct()` and `idct()`. 
- [ ] Implement the existing DCT approach from the `main` branch, using `scipy.dct` and `scipy.idct`
- [ ] Create autogenerated unit tests that find different implementations of DCT
- [ ] Create autogenerated benchmarks that run different implementations of the DCT

**Comment by tdmorello** [comment]
Should we incorporate a global OR enc variable into this like `DCT_BACKEND`?

Then use something like `dct_factory` with `DCT_BACKEND` determining the concrete `DCT` class.
