### ISSUE TITLE
Implement `BaSiC.predict()`

### ISSUE THREAD

**Issue by Nicholas-Schaub** [peng-lab/BaSiCpy#22]
Implement a baseline `BaSiC.predict()` that takes a stack of images as a `np.ndarray` and outputs an `np.ndarray` of corrected images.

- [ ] Implement a baseline `BaSiC.predict()` method
- [ ] Create a unit test for `BaSiC.predict()` (should not rely on `BaSiC.fit()`)

**Comment by yfukai** [comment]
#14 can be a comment for this.
