### ISSUE TITLE
Repo Cleanup

### ISSUE THREAD

**Issue by Nicholas-Schaub** [peng-lab/BaSiCPy#31]
Some items should be removed. For example, `profile.py` and associated tests.

The name of the folder inside of `src` should be changed from `pybasic` -> `BaSiCpy`. Currently, when the package is installed it is imported using `pybasic`, which creates confusion when the install is `pip install BaSiCpy`. This change may require some code changes.

Since this package is not significantly layered, I also propose we get rid of relative imports to be more explicit about what is getting imported and from where.

**Comment by Nicholas-Schaub** [comment]
Partially resolved by #37

**Comment by yfukai** [comment]
I think this is basically solved by #51 . Feel free to open again if this is not the case.
