### ISSUE TITLE
Make sure package is built with dask compatibility

### ISSUE THREAD

**Issue by tdmorello** [peng-lab/BaSiCPy#6]

**Comment by yfukai** [comment]
I think this will be useful for lazy-loading dataset we discussed. With dask compatibility, we might even not need our custom image loading functionality.

**Comment by yfukai** [comment]
https://github.com/google/jax/issues/395
It seems that JAX needs the data to be on-memory for now.

**Comment by yfukai** [comment]
For `transform`, we can definitely make it compatible with dask.

**Comment by yfukai** [comment]
done in #80
