### ISSUE TITLE
Timelapse illumination correction method [MICCAI 2020]

### ISSUE THREAD

**Issue by gwaybio** [peng-lab/BaSiCPy#65]
Hi @tying84 and @Mirkazemi - Thanks for making BASIC available for python.

 In your 2020 paper ["Background and Illumination Correction for Time-Lapse Microscopy Data with Correlated Foreground"](https://link.springer.com/chapter/10.1007/978-3-030-59722-1_17) you introduce an improved method for illumination correction in timelapse imaging.

Is code for this updated method available in python? The paper states: 

> We will also develop our method into a user-friendly software tool that a large biological community can benefit from.

Can you point me to this resource? @roshankern and I are very interested in applying your method! Thank you in advance

**Comment by yfukai** [comment]
Hi, thank you @gwaygenomics for your interest!
We, @Nicholas-Schaub, @tdmorello, @tying84, and I, are now trying to develop a brand-new version in the `dev` branch. That method and some improved implementation will also be provided there. 
Please wait for one or two months until it gets completed!

**Comment by gwaygenomics** [comment]
Thanks @yfukai - we look forward to applying your implementation.

**Comment by tying84** [comment]
The BaSiC code is already in Python. The one with the segmentation mask
will also be added in a few weeks.

Tingying

Gregory Way ***@***.***> schrieb am Fr. 27. Mai 2022 um 18:50:

**Comment by yfukai** [comment]
Implemented for the beta release! Please check out the `fitting_weight` parameter. @gwaybio 
https://basicpy.readthedocs.io/en/latest/api.html#basicpy.basicpy.BaSiC.fit

**Comment by gwaybio** [comment]
perfect! Thanks @yfukai - @jenna-tomkinson, @roshankern, and I are looking forward to testing this out!
