### ISSUE TITLE
Changing settings doesn't work

### ISSUE THREAD

**Issue by dataMaster-Kris** [peng-lab/BaSiCPy#67]
Hi,

For some of my images, the flatfield and darkfield estimates were `nan` after running basic with the default settings. So I changed the settings as follows:

    from pybasic import settings
    settings.max_reweight_iterations = 20

However, rerunning basic in the same session still terminates after 10 iterations. Any suggestions? Thanks in advance.

**Comment by yfukai** [comment]
Hi thanks @dataMaster-Kris for your interest! I guess you're using the old version (`main` branch) of the code. That version is not in active development and a new version at `dev` branch will soon be released. Please be patient for one month or so.
