### ISSUE TITLE
Test data migration

### ISSUE THREAD

**Issue by yfukai** [peng-lab/BaSiCPy#8]
We would like to migrate large test data out of the repository. There're two things to decide:
- where to put the data
- how we can delete existing large data from the repo (or do we need to?)

**Comment by tdmorello** [comment]
Whenever we get a chance, we should register for a zenodo account. It should probably be @tying84 's

**Comment by yfukai** [comment]
Thanks @tdmorello for your comment! My Zenodo account is yfukai just in case.

**Comment by yfukai** [comment]
Zenodo dataset is already created: https://doi.org/10.5281/zenodo.6334810
The remaining task is to clean up the data in the current repo.
