### ISSUE TITLE
Decide the shape for the `flatfield` and `darkfield`

### ISSUE THREAD

**Issue by yfukai** [peng-lab/BaSiCPy#85]
I think it would be a bit more intuitive if we make `basic.flatfield`  and `basic.darkfield` the same shape as the input images. We need discussion on this specification.

**Comment by tdmorello** [comment]
I think that would make more sense. I always saw the reshaping to square as an intermediate step.

**Comment by yfukai** [comment]
I'll make a PR in this way.
