### ISSUE TITLE
Repository name

### ISSUE THREAD

**Issue by yfukai** [peng-lab/BaSiCpy#9]
We decided on the name as BaSiCpy. Isn't the repository name confusing? Shall we change it to BaSiCpy?

**Comment by tdmorello** [comment]
I'll add that we should register basicpy on readthedocs as well

**Comment by yfukai** [comment]
Is this fine for you, @Nicholas-Schaub, @YuLiu-web, and @tim

**Comment by Nicholas-Schaub** [comment]
Works for me.

**Comment by yfukai** [comment]
Sorry, I noticed PyPi name is actually BaSiCpy and I think it's better if it's the same.
Unfortunately, I don't have the admin right to rename the repo. Would you mind renaming the repo to that @Nicholas-Schaub?

**Comment by Nicholas-Schaub** [comment]
I think I can change it, but functionally it shouldn't matter because case doesn't matter in pip.

**Comment by Nicholas-Schaub** [comment]
Done.
