### ISSUE TITLE
Sample data value overflow

### ISSUE THREAD

**Issue by tdmorello** [peng-lab/BaSiCPy#90]
Some sample data seem to have overflow of integer values (see black pixels in the center of cells). This usually happens when an integer value is above the upper bound of what N bits can represent. Likely occurred during some conversion of 16 to 8 bits.

<img width="1552" alt="Screen Shot 2022-07-06 at 9 50 29 AM" src="https://user-images.githubusercontent.com/34800427/177569270-093f0a0e-620c-444f-8d9e-d73d9067c6c8.png">

**Comment by yfukai** [comment]
Thanks, I'll replace the data!

**Comment by yfukai** [comment]
closed in #92
