### ISSUE TITLE
Saving Corrected Images Example

### ISSUE THREAD

**Issue by jenna-tomkinson** [peng-lab/BaSiCPy#91]
Hello @yfukai,

I appreciated the help you gave in #81. I am one of the biologists within the @gwaybio lab and I was wondering if you could provide some clarification. I noticed that the examples provided do not show how to extract the corrected images and save them into a file. Is there a preferred method of saving that works best for BaSiCPy (i.e skimage.io.imsave or plt.savefig)?

I noticed that when I was using plt.savefig for saving the images, the outputted images were much smaller than the original. Is this to be expected?

Thank you!
Jenna

**Comment by yfukai** [comment]
Hi @jenna-tomkinson, thank you for your interest! The default output will be float32, and I recommend saving this in a format which is capable of preserving its data. 
- I don't recommend plt.savefig as it doesn't save the raw data (it just saves the plotted version with the specified color map)
- TIFF (through tifffile or skimage.io.imsave) is a good option but saving multiple channel might be tricky. I recommend saving each channel to a single image file https://stackoverflow.com/questions/57932630/save-32-bit-floating-point-tiff-image 
- If the downstream analysis is done in Python, using .npy or HDF5 format is the best choice as it works most stable.

**Comment by yfukai** [comment]
I think we can add this to example notebooks. Re-open for now as a reminder.

**Comment by jenna-tomkinson** [comment]
Hi @yfukai,

Thank you for opening this back up! My lab is very interested in your method for saving the images and we are excited to be able to compare it to our method. You can view the existing solution we have here: https://github.com/WayScience/NF1_SchwannCell_data/blob/main/1_preprocessing_data/PyBaSiC_Pipelines/Illumination_Correction.ipynb.

Thank you for your work on this package!

Jenna Tomkinson

**Comment by yfukai** [comment]
Hi thanks @jenna-tomkinson for your update!, it seems that you're using the older version of `BaSiCPy`. There will come the newer version (now developed in the `dev` branch) and I think the performance would change with that (as we have an algorithm update, but the original algorithm can also be used.). I'll update you as soon as we get to the release. (You can already install it from GitHub as `pip install git+https://github.com/peng-lab/BaSiCPy@dev` though)

**Comment by yfukai** [comment]
The newer version will be found here.
https://github.com/peng-lab/BaSiCPy/tree/dev

**Comment by yfukai** [comment]
Closing for new. Feel free to reopen.
